openapi: 3.0.3
info:
  title: Tiny Example API 3
  version: 1.0.0

servers:
  - url: https://api.example.com

paths:
  /health:
    get:
      summary: Health check 1
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                required: [status]
              example:
                status: ok
