openapi: 3.0.3
info:
  title: Tiny Example API 3
  version: 1.0.0

servers:
  - url: https://api.example.com

paths:
  /health:
    get:
      summary: Health check 5
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                required: [status]
              example:
                status: ok

  /info:
    get:
      summary: API information
      responses:
        "200":
          description: API metadata
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  version:
                    type: string
                required: [name, version]
              example:
                name: Tiny Example API 3
                version: 1.0.0
