openapi: 3.0.3
info:
  title: Tiny Example API 3
  version: 1.1.0

servers:
  - url: https://api.example.com

paths:
  /health:
    get:
      summary: Service health check endpoint
      parameters:
        - name: verbose
          in: query
          required: false
          schema:
            type: boolean
          description: Include detailed health info
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  uptime:
                    type: integer
                required: [status]
              example:
                status: ok
                uptime: 3600

  /status:
    get:
      summary: Get system status
      responses:
        "200":
          description: System status
          content:
            application/json:
              schema:
                type: object
                properties:
                  database:
                    type: string
                  cache:
                    type: string
                required: [database, cache]
              example:
                database: connected
                cache: active

  /users:
    get:
      summary: List all users
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
      responses:
        "200":
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    email:
                      type: string
                  required: [id, email]
              example:
                - id: "1"
                  email: user@example.com

    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                name:
                  type: string
              required: [email]
            example:
              email: newuser@example.com
              name: New User
      responses:
        "201":
          description: User created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
                  name:
                    type: string
                required: [id, email]
              example:
                id: "2"
                email: newuser@example.com
                name: New User

  /items:
    post:
      summary: Add an item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required: [name]
            example:
              name: Sample item
      responses:
        "201":
          description: Item created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                required: [id, name]
              example:
                id: "123"
                name: Sample item

  /items/{id}:
    put:
      summary: Modify an item
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required: [name]
            example:
              name: Updated item
      responses:
        "200":
          description: Item updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                required: [id, name]
              example:
                id: "123"
                name: Updated item

    delete:
      summary: Delete an item
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Item deleted
