openapi: 3.0.3
info:
  title: Tiny Example API 3
  version: 1.0.0

servers:
  - url: https://api.example.com

paths:
  /health:
    get:
      summary: Health check 5
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                required: [status]
              example:
                status: ok

  /info:
    get:
      summary: API information
      responses:
        "200":
          description: API metadata
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  version:
                    type: string
                required: [name, version]
              example:
                name: Tiny Example API 3
                version: 1.0.0

  /items:
    post:
      summary: Add an item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required: [name]
            example:
              name: Sample item
      responses:
        "201":
          description: Item created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                required: [id, name]
              example:
                id: "123"
                name: Sample item

  /items/{id}:
    put:
      summary: Modify an item
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required: [name]
            example:
              name: Updated item
      responses:
        "200":
          description: Item updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                required: [id, name]
              example:
                id: "123"
                name: Updated item

    delete:
      summary: Delete an item
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Item deleted
